#This program says hello and asks for your job
print('Hello, stranger!')
print('What is your name?')
myName = input()
print('Welcome on board, ' + str(myName)) 
print('Tell me more details about you ' + str(myName) + '. What is your job?')
myJob = input()
print(str(myJob) + ', Nice one! How long have you been doing that for?')
jobAge = input()
print('Wow ' + str(int(jobAge)) + ' years! You are becoming a part of the furniture!')  
